export const $ = (selector) => document.querySelector(selector);

export const dom = {
  canvas: $("#scene"),
  loading: $("#loading-screen"),
  loadingStatus: $("#loading-status"),
  loadingFill: $("#loading-fill"),
  loadingTrack: $(".loading-track"),
  loadingActions: $("#loading-actions"),
  hud: $("#hud"),
  languageToggle: $("#language-toggle"),
  anchorProgress: $("#anchor-progress"),
  anchorImages: [...document.querySelectorAll("#anchor-progress img")],
  helm: $("#helm"),
  helmGuide: $("#helm-guide"),
  helmGuideDot: $("#helm-guide-dot"),
  helmGuideText: $("#helm-guide-text"),
  dangerWarning: $("#danger-warning"),
  dangerCode: $("#danger-code"),
  dangerText: $("#danger-text"),
  emergencyButton: $("#emergency-button"),
  emergencyLabel: $("#emergency-label"),
  popupBackdrop: $("#popup-backdrop"),
  popupPanel: $("#popup-panel"),
  popupDragHandle: $("#popup-drag-handle"),
  popupKicker: $("#popup-kicker"),
  popupTitle: $("#popup-title"),
  popupIndex: $("#popup-index"),
  popupContent: $("#popup-content"),
  popupBody: $("#popup-body"),
  popupClose: $("#popup-close"),
  compassNeedle: $("#compass-needle"),
};
